# fly.toml app configuration file generated for retirement-calculator-dev on 2024-01-25T20:29:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'retirement-calculator-dev'
primary_region = 'atl'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 80
    handlers = ['http']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
